#!/usr/bin/env bash
# a Bash script that installs nginx on our web-01 server
# /redirect_me is redirecting to another page
sudo apt-get -y update
sudo apt-get -y install nginx
myc="\n\trewrite \^\/redirect_me\/\$ https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent\;"
st="server {"
sudo sed -i "0,/$st/{s/$st/$st$myc/}" /etc/nginx/sites-enabled/default
sudo service nginx start
